name: npm-publish
on:
  release:
    types: [created]

jobs:
  my-job:
    name: publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - uses: actions/setup-node@v2
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - run: chmod +x ./scripts/build.sh
      - run: ./scripts/build.sh ${{ github.event.release.tag_name }}
      # - run: npm publish
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
